# Where things are
source: .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir: ./_data
includes_dir: ./_includes

# this config will lead github pages blog(jekyll 3.0.3) generate no rendered posts
# so comment out this until github used jekyll updated
# collections: null

# Handling Reading
safe: false
include: [".htaccess"]
exclude: []
keep_files: [".git", ".svn"]
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future: true
unpublished: false

# Plugins
whitelist: []
gems:
  - jekyll-feed
  - jekyll-sitemap

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Outputting
permalink: /:year/:month/:title.html
# paginate: 8
paginate_path: /page:num
timezone: Asia/Shanghai

feed:
  path: feed.xml

quiet: false
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      comments: true
  -
    scope:
      path: ""      # empty string for all files
      type: pages   # limit to posts
    values:
      comments: false

# Markdown Processors
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  enable_coderay: false

#iLotus configs
iLotus:
  columns: 1
  begin: 2015

  # comments provider
  # comments:
  #   provider: disqus
  #   duoshuo:
  #     short_name:
  #   disqus:
  #     short_name: isaymesite

  archives_path: /archives.html
  contact_path: /contact.html
  links_path: /links.html
  tags_path: /tags.html

  #菜单配置
  navs:
    - text: 首页
      url: /
      icon: fa fa-home
      class: home
    - text: 文章归档
      url: /archives.html
      icon: fa fa-reorder
      class: none
    - text: 文章标签
      url: /tags.html
      icon: fa fa-tags
      class: none
    - text: 关于我
      url: /contact.html
      icon: fa fa-user
      class: none
    - text: 博客源代码
      url: https://github.com/zchbluetear/zchbluetear.github.io
      icon: fa fa-github-square
      class: none

#站点基础配置
title: 自说Me话
subTitle: 求知若饥 | 虚怀若愚 | 简单可依赖
description: java开发
keywords: 技术&生活
url: https://piecetime.cn/

author:
  name : Mr.Zhang
  email: 1424490125@qq.com
  github: zchbluetear
  QQ: 1424490125
